name: Profile Gotchi

on:
  schedule:
    - cron: '0 */6 * * *' # Updates every 6 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  update-pet:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Pet ðŸ‘¾
        uses: ThanhNguyxn/Git-Gotchi@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}
          
      - name: Commit & Push ðŸ’¾
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/pet.svg
          git commit -m "Update Profile-Gotchi ðŸ‘¾" || exit 0
          git push
